version: '3.5'

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  mysql-volume:

services:
  app:
    container_name: frontend-angular
    image: 10082020/app-device-category:angular
    networks:
      - app-network
    ports:
      - 8080:8080
  
  api:
    container_name: backend-node
    image: 10082020/app-device-category:node
    networks:
      - app-network
    depends_on:
      - database
    ports:
      - 3000:3000
    environment:
      HOSTNAME: '172.17.0.1'
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: device_category
      MYSQL_PORT: '3306'
      PORT: '3000'

  database:
    container_name: database-mysql
    image: 10082020/app-device-category:mysql
    networks:
      - app-network
    ports:
      - 3306:3306
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: device_category
      
